version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3007"
    image: ais-portals
    environment:
      - DATABASE_URL=postgresql://root:arunnya151007*@quantumx.arunnya.com:5432/quantumx-submissions
  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8080:3008"
    volumes:
      - ./public/submissions:/usr/share/nginx/submissions:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro