version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3007:3000"
    image: quantumx-submissions
    environment:
      - DATABASE_URL=postgresql://root:arunnya151007*@quantumx.arunnya.com:5432/quantumx-submissions
  nginx:
    image: nginx:latest
    container_name: quantumx-submissions-server
    ports:
      - "3008:80"
    volumes:
      - ./public/submissions:/usr/share/nginx/submissions:rw
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:rw